2021-10-07 17:23:08 [main] ERROR epam.task1.reader.impl.InfoReaderImpl - The data source testdata//test.txt was not found or unable to open
java.io.FileNotFoundException: testdata\test.txt (Системе не удается найти указанный путь)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:108) ~[?:?]
	at java.io.FileReader.<init>(FileReader.java:60) ~[?:?]
	at by.epam.task1.reader.impl.InfoReaderImpl.readLine(InfoReaderImpl.java:23) ~[classes/:?]
	at test.by.epam.task1.reader.InfoReaderTest.readLineTest(InfoReaderTest.java:19) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
2021-10-07 17:29:07 [main] ERROR epam.task1.reader.impl.InfoReaderImpl - The data source data\info.txt was not found or unable to open
java.io.FileNotFoundException: data\info.txt (Системе не удается найти указанный путь)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:108) ~[?:?]
	at java.io.FileReader.<init>(FileReader.java:60) ~[?:?]
	at by.epam.task1.reader.impl.InfoReaderImpl.readLine(InfoReaderImpl.java:23) [classes/:?]
	at by.epam.task1.main.Main.main(Main.java:31) [classes/:?]
2021-10-07 17:29:07 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException: The data source data\info.txt was not found or unable to open
2021-10-07 17:54:41 [main] ERROR epam.task1.reader.impl.InfoReaderImpl - The data source gfd,43,-2,
76,89,yu!,6,
45,-3,34,56,22,56,-100,35
8,9,-5,43,e was not found or unable to open
java.io.FileNotFoundException: gfd,43,-2,
76,89,yu!,6,
45,-3,34,56,22,56,-100,35
8,9,-5,43,e (Синтаксическая ошибка в имени файла, имени папки или метке тома)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:108) ~[?:?]
	at java.io.FileReader.<init>(FileReader.java:60) ~[?:?]
	at by.epam.task1.reader.impl.InfoReaderImpl.readLine(InfoReaderImpl.java:23) [classes/:?]
	at by.epam.task1.main.Main.main(Main.java:37) [classes/:?]
2021-10-07 17:54:41 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException: The data source gfd,43,-2,
76,89,yu!,6,
45,-3,34,56,22,56,-100,35
8,9,-5,43,e was not found or unable to open
2021-10-07 18:20:56 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException
2021-10-07 18:23:57 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException
2021-10-07 18:24:43 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException
2021-10-07 18:27:14 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException
2021-10-07 18:27:35 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException
2021-10-07 18:27:49 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException
2021-10-07 18:28:07 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException
2021-10-07 18:28:36 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException
2021-10-07 18:30:19 [main] ERROR epam.task1.reader.impl.InfoReader2Impl - invalid path 
java.nio.file.NoSuchFileException: .\data\info.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4104) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4196) ~[?:?]
	at by.epam.task1.reader.impl.InfoReader2Impl.readLine(InfoReader2Impl.java:26) [classes/:?]
	at by.epam.task1.main.Main.main(Main.java:36) [classes/:?]
2021-10-07 18:30:19 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException: invalid path 
2021-10-07 18:31:02 [main] ERROR epam.task1.reader.impl.InfoReader2Impl - invalid path 
java.nio.file.NoSuchFileException: info.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4104) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4196) ~[?:?]
	at by.epam.task1.reader.impl.InfoReader2Impl.readLine(InfoReader2Impl.java:26) [classes/:?]
	at by.epam.task1.main.Main.main(Main.java:36) [classes/:?]
2021-10-07 18:31:02 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException: invalid path 
2021-10-07 18:31:29 [main] ERROR epam.task1.reader.impl.InfoReader2Impl - invalid path 
java.nio.file.NoSuchFileException: \info.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4104) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4196) ~[?:?]
	at by.epam.task1.reader.impl.InfoReader2Impl.readLine(InfoReader2Impl.java:26) [classes/:?]
	at by.epam.task1.main.Main.main(Main.java:36) [classes/:?]
2021-10-07 18:31:29 [main] ERROR by.epam.task1.main.Main - by.epam.task1.exception.CustomArrayException: invalid path 
2021-10-07 18:49:22 [main] ERROR epam.task1.reader.impl.InfoReaderImpl - The data source data\noFile.txt was not found or unable to open
java.io.FileNotFoundException: data\noFile.txt (Не удается найти указанный файл)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:108) ~[?:?]
	at java.io.FileReader.<init>(FileReader.java:60) ~[?:?]
	at by.epam.task1.reader.impl.InfoReaderImpl.readLine(InfoReaderImpl.java:23) ~[classes/:?]
	at test.by.epam.task1.reader.InfoReaderTest.readLineNoFileTest(InfoReaderTest.java:24) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
